import {
  AlertTriangle,
  ClipboardCheck,
  ClipboardList,
  FileCheck,
  FileText,
  Gauge,
  History,
  Link2,
  PackageCheck,
  ScrollText,
  ShieldCheck,
  Truck,
  Users,
} from 'lucide-react';

export const medsupplierSections = [
  {
    key: 'accounts',
    label: 'Cliente 360',
    resource: 'accounts',
    icon: Users,
    description: 'Cuentas Supplier-Customer, clasificación regulada, riesgo y visibilidad shared/private.',
    columns: [
      ['name', 'Cuenta'],
      ['account_code', 'Código'],
      ['status', 'Estado'],
      ['risk_level', 'Riesgo'],
      ['visibility', 'Visibilidad'],
    ],
  },
  {
    key: 'meetings',
    label: 'Reuniones',
    resource: 'meetings',
    icon: ClipboardCheck,
    description: 'Reuniones, minutas, decisiones y evidencia de seguimiento con cliente/proveedor.',
    columns: [
      ['title', 'Reunión'],
      ['status', 'Estado'],
      ['meeting_date', 'Fecha'],
      ['visibility', 'Visibilidad'],
    ],
  },
  {
    key: 'actions',
    label: 'Acciones',
    resource: 'actions',
    icon: ClipboardList,
    description: 'Acciones abiertas, responsables, vencimientos y trazabilidad de cierre.',
    columns: [
      ['title', 'Acción'],
      ['owner', 'Responsable'],
      ['due_date', 'Vence'],
      ['status', 'Estado'],
    ],
  },
  {
    key: 'requirements',
    label: 'Requisitos',
    resource: 'requirements',
    icon: ScrollText,
    description: 'Requisitos de cliente, regulatorios y técnicos conectados a RFQ, documentos y evidencia.',
    columns: [
      ['requirement_id', 'ID'],
      ['title', 'Requisito'],
      ['requirement_type', 'Tipo'],
      ['status', 'Estado'],
    ],
  },
  {
    key: 'documents',
    label: 'Document Room',
    resource: 'documents',
    icon: FileText,
    description: 'Documentos controlados, estado vigente/obsoleto, confidencialidad y versión vigente.',
    columns: [
      ['document_number', 'Documento'],
      ['title', 'Título'],
      ['current_revision', 'Rev.'],
      ['status', 'Estado'],
    ],
  },
  {
    key: 'rfqs',
    label: 'RFQ',
    resource: 'rfqs',
    icon: FileCheck,
    description: 'Solicitudes de cotización y requisitos asociados.',
    columns: [
      ['rfq_number', 'RFQ'],
      ['title', 'Título'],
      ['status', 'Estado'],
      ['requested_due_date', 'Fecha requerida'],
    ],
  },
  {
    key: 'quotes',
    label: 'Cotizaciones',
    resource: 'quotes',
    icon: Gauge,
    description: 'Cotizaciones controladas, montos, vigencia y visibilidad privada/comercial.',
    columns: [
      ['quote_number', 'Cotización'],
      ['status', 'Estado'],
      ['currency', 'Moneda'],
      ['total_amount', 'Monto'],
    ],
  },
  {
    key: 'orders',
    label: 'Órdenes',
    resource: 'purchase-orders',
    icon: PackageCheck,
    description: 'POs, fechas prometidas, estado operativo y trazabilidad hacia lotes y shipments.',
    columns: [
      ['po_number', 'PO'],
      ['status', 'Estado'],
      ['promised_ship_date', 'Fecha promesa'],
      ['total_amount', 'Monto'],
    ],
  },
  {
    key: 'shipments',
    label: 'Shipments',
    resource: 'shipments',
    icon: Truck,
    description: 'Entregas, tracking, carrier y estado logístico compartido.',
    columns: [
      ['shipment_number', 'Shipment'],
      ['status', 'Estado'],
      ['carrier', 'Carrier'],
      ['tracking_number', 'Tracking'],
    ],
  },
  {
    key: 'quality',
    label: 'Calidad',
    resource: 'quality-events',
    icon: AlertTriangle,
    description: 'NCR, quejas, desviaciones y hallazgos conectados a inspecciones y CAPA.',
    columns: [
      ['event_number', 'Evento'],
      ['event_type', 'Tipo'],
      ['severity', 'Severidad'],
      ['status', 'Estado'],
    ],
  },
  {
    key: 'capas',
    label: 'CAPA',
    resource: 'capas',
    icon: ShieldCheck,
    description: 'CAPA básica, causa raíz, acciones correctivas/preventivas y verificación de efectividad.',
    columns: [
      ['capa_number', 'CAPA'],
      ['status', 'Estado'],
      ['owner', 'Responsable'],
      ['due_date', 'Vence'],
    ],
  },
  {
    key: 'scorecards',
    label: 'Scorecards',
    resource: 'scorecards',
    icon: Gauge,
    description: 'Desempeño de calidad, entrega, respuesta y QBR.',
    columns: [
      ['period_start', 'Desde'],
      ['period_end', 'Hasta'],
      ['overall_score', 'Score'],
      ['visibility', 'Visibilidad'],
    ],
  },
  {
    key: 'audit',
    label: 'Audit Trail',
    resource: 'audit-events',
    icon: History,
    description: 'Eventos auditables exportables del módulo MedSupplier.',
    columns: [
      ['created_at', 'Fecha'],
      ['action', 'Acción'],
      ['record_type', 'Registro'],
      ['description', 'Descripción'],
    ],
  },
  {
    key: 'integration',
    label: 'Integración',
    resource: null,
    icon: Link2,
    description: 'AdminApps gobierna organizaciones, usuarios, roles, licencias y habilitación del producto MEDSUPPLIER.',
    columns: [],
  },
];

export const getMedSupplierSection = (key) => (
  medsupplierSections.find((section) => section.key === key) || medsupplierSections[0]
);
