import {
  AlertTriangle,
  ClipboardCheck,
  ClipboardList,
  FileCheck,
  FileText,
  Gauge,
  History,
  Link2,
  PackageCheck,
  ScrollText,
  ShieldCheck,
  Truck,
  Users,
} from 'lucide-react';

export const medsupplierVisibilityOptions = [
  ['public_shared', 'Compartido público controlado'],
  ['customer_shared', 'Compartido con cliente'],
  ['supplier_private', 'Privado Supplier'],
  ['supplier_confidential', 'Confidencial Supplier'],
  ['regulated_evidence', 'Evidencia regulada'],
  ['audit_only', 'Solo auditoría'],
  ['archived', 'Archivado'],
  ['obsolete', 'Obsoleto'],
];

export const medsupplierSections = [
  {
    key: 'cockpit',
    label: 'Cockpit privado',
    resource: null,
    icon: Gauge,
    description: 'Resumen comercial privado Supplier para margen, forecast, aging, oportunidades y riesgo.',
    columns: [],
    requiresPermission: 'can_access_supplier_cockpit',
  },
  {
    key: 'accounts',
    label: 'Cliente 360',
    resource: 'accounts',
    icon: Users,
    description: 'Cuentas Supplier-Customer, clasificación regulada, riesgo y visibilidad shared/private.',
    columns: [
      ['name', 'Cuenta'],
      ['account_code', 'Código'],
      ['status', 'Estado'],
      ['risk_level', 'Riesgo'],
      ['visibility', 'Visibilidad'],
    ],
    formFields: [
      { name: 'name', label: 'Cuenta', type: 'text', required: true },
      { name: 'account_code', label: 'Código', type: 'text', required: true },
      { name: 'legal_name', label: 'Razón social', type: 'text' },
      { name: 'customer_segment', label: 'Segmento', type: 'text' },
      { name: 'country', label: 'País', type: 'text' },
      { name: 'primary_contact_email', label: 'Email principal', type: 'email' },
      { name: 'account_owner', label: 'Responsable interno', type: 'text' },
      {
        name: 'status',
        label: 'Estado',
        type: 'select',
        defaultValue: 'active',
        options: [
          ['prospect', 'Prospecto'],
          ['active', 'Activo'],
          ['on_hold', 'En espera'],
          ['disqualified', 'Descalificado'],
          ['inactive', 'Inactivo'],
        ],
      },
      {
        name: 'risk_level',
        label: 'Nivel de riesgo',
        type: 'select',
        defaultValue: 'medium',
        options: [
          ['low', 'Bajo'],
          ['medium', 'Medio'],
          ['high', 'Alto'],
          ['critical', 'Crítico'],
        ],
      },
      { name: 'next_qbr_date', label: 'Próximo QBR', type: 'date' },
      { name: 'regulated_industry', label: 'Industria regulada', type: 'checkbox', defaultValue: true },
      {
        name: 'visibility',
        label: 'Visibilidad',
        type: 'select',
        defaultValue: 'shared',
        options: [
          ['shared', 'Compartido Supplier-Customer'],
          ['private', 'Privado interno'],
        ],
      },
    ],
    workflowActions: [
      { action: 'generate-qbr', label: 'Generar QBR', confirm: '¿Generar scorecard/QBR para esta cuenta?' },
    ],
  },
  {
    key: 'contacts',
    label: 'Contactos',
    resource: 'contacts',
    icon: Users,
    description: 'Contactos por cuenta, rol, departamento, canal de contacto y estado de relacion.',
    columns: [
      ['full_name', 'Contacto'],
      ['email', 'Email'],
      ['role_title', 'Rol'],
      ['department', 'Departamento'],
      ['is_active', 'Activo'],
    ],
    formFields: [
      {
        name: 'account',
        label: 'Cuenta',
        type: 'relation',
        resource: 'accounts',
        required: true,
        optionFields: ['account_code', 'name'],
      },
      { name: 'full_name', label: 'Nombre completo', type: 'text', required: true },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'role_title', label: 'Rol / puesto', type: 'text' },
      { name: 'department', label: 'Departamento', type: 'text' },
      { name: 'phone', label: 'Teléfono', type: 'text' },
      { name: 'is_customer_user', label: 'Usuario cliente', type: 'checkbox', defaultValue: true },
      { name: 'is_active', label: 'Contacto activo', type: 'checkbox', defaultValue: true },
      {
        name: 'visibility',
        label: 'Visibilidad',
        type: 'select',
        defaultValue: 'shared',
        options: [
          ['shared', 'Compartido Supplier-Customer'],
          ['private', 'Privado interno'],
        ],
      },
    ],
  },
  {
    key: 'meetings',
    label: 'Reuniones',
    resource: 'meetings',
    icon: ClipboardCheck,
    description: 'Reuniones, minutas, decisiones y evidencia de seguimiento con cliente/proveedor.',
    columns: [
      ['title', 'Reunión'],
      ['status', 'Estado'],
      ['meeting_date', 'Fecha'],
      ['visibility', 'Visibilidad'],
    ],
    formFields: [
      {
        name: 'account',
        label: 'Cuenta',
        type: 'relation',
        resource: 'accounts',
        required: true,
        optionFields: ['account_code', 'name'],
      },
      { name: 'title', label: 'Título', type: 'text', required: true },
      { name: 'meeting_date', label: 'Fecha y hora', type: 'datetime-local', required: true },
      {
        name: 'status',
        label: 'Estado',
        type: 'select',
        defaultValue: 'planned',
        options: [
          ['planned', 'Planificada'],
          ['completed', 'Completada'],
          ['cancelled', 'Cancelada'],
        ],
      },
      { name: 'agenda', label: 'Agenda', type: 'textarea' },
      { name: 'minutes', label: 'Minutas', type: 'textarea' },
      {
        name: 'visibility',
        label: 'Visibilidad',
        type: 'select',
        defaultValue: 'shared',
        options: [
          ['shared', 'Compartido Supplier-Customer'],
          ['private', 'Privado interno'],
        ],
      },
    ],
  },
  {
    key: 'actions',
    label: 'Acciones',
    resource: 'actions',
    icon: ClipboardList,
    description: 'Acciones abiertas, responsables, vencimientos y trazabilidad de cierre.',
    columns: [
      ['title', 'Acción'],
      ['owner', 'Responsable'],
      ['due_date', 'Vence'],
      ['status', 'Estado'],
    ],
    formFields: [
      {
        name: 'account',
        label: 'Cuenta',
        type: 'relation',
        resource: 'accounts',
        required: true,
        optionFields: ['account_code', 'name'],
      },
      {
        name: 'meeting',
        label: 'Reunión relacionada',
        type: 'relation',
        resource: 'meetings',
        optionFields: ['title'],
      },
      { name: 'title', label: 'Acción', type: 'text', required: true },
      { name: 'owner', label: 'Responsable', type: 'text' },
      { name: 'due_date', label: 'Fecha vencimiento', type: 'date' },
      {
        name: 'status',
        label: 'Estado',
        type: 'select',
        defaultValue: 'open',
        options: [
          ['open', 'Abierta'],
          ['in_progress', 'En progreso'],
          ['blocked', 'Bloqueada'],
          ['closed', 'Cerrada'],
        ],
      },
      { name: 'description', label: 'Descripción', type: 'textarea' },
      {
        name: 'visibility',
        label: 'Visibilidad',
        type: 'select',
        defaultValue: 'shared',
        options: [
          ['shared', 'Compartido Supplier-Customer'],
          ['private', 'Privado interno'],
        ],
      },
    ],
  },
  {
    key: 'requirements',
    label: 'Requisitos',
    resource: 'requirements',
    icon: ScrollText,
    description: 'Requisitos de cliente, regulatorios y técnicos conectados a RFQ, documentos y evidencia.',
    columns: [
      ['requirement_id', 'ID'],
      ['title', 'Requisito'],
      ['requirement_type', 'Tipo'],
      ['status', 'Estado'],
    ],
    formFields: [
      {
        name: 'account',
        label: 'Cuenta',
        type: 'relation',
        resource: 'accounts',
        required: true,
        optionFields: ['account_code', 'name'],
      },
      { name: 'requirement_id', label: 'ID del requisito', type: 'text', required: true },
      { name: 'title', label: 'Título', type: 'text', required: true },
      { name: 'requirement_type', label: 'Tipo', type: 'text', defaultValue: 'customer' },
      { name: 'source_reference', label: 'Referencia fuente', type: 'text' },
      { name: 'description', label: 'Descripción', type: 'textarea', required: true },
      {
        name: 'status',
        label: 'Estado',
        type: 'select',
        defaultValue: 'draft',
        options: [
          ['draft', 'Borrador'],
          ['under_review', 'En revisión'],
          ['approved', 'Aprobado'],
          ['superseded', 'Reemplazado'],
          ['obsolete', 'Obsoleto'],
        ],
      },
      { name: 'effective_date', label: 'Fecha efectiva', type: 'date' },
      { name: 'owner', label: 'Responsable', type: 'text' },
      {
        name: 'visibility',
        label: 'Visibilidad',
        type: 'select',
        defaultValue: 'shared',
        options: [
          ['shared', 'Compartido Supplier-Customer'],
          ['private', 'Privado interno'],
        ],
      },
    ],
  },
  {
    key: 'documents',
    label: 'Document Room',
    resource: 'documents',
    icon: FileText,
    description: 'Documentos controlados, estado vigente/obsoleto, confidencialidad y versión vigente.',
    columns: [
      ['document_number', 'Documento'],
      ['title', 'Título'],
      ['current_revision', 'Rev.'],
      ['status', 'Estado'],
    ],
    formFields: [
      {
        name: 'account',
        label: 'Cuenta',
        type: 'relation',
        resource: 'accounts',
        required: true,
        optionFields: ['account_code', 'name'],
      },
      { name: 'document_number', label: 'Número de documento', type: 'text', required: true },
      { name: 'title', label: 'Título', type: 'text', required: true },
      { name: 'document_type', label: 'Tipo de documento', type: 'text', required: true },
      { name: 'current_revision', label: 'Revisión vigente', type: 'text', defaultValue: 'A' },
      {
        name: 'status',
        label: 'Estado',
        type: 'select',
        defaultValue: 'draft',
        options: [
          ['draft', 'Borrador'],
          ['under_review', 'En revisión'],
          ['effective', 'Vigente'],
          ['obsolete', 'Obsoleto'],
        ],
      },
      { name: 'confidentiality', label: 'Confidencialidad', type: 'text', defaultValue: 'controlled' },
      { name: 'owner', label: 'Responsable', type: 'text' },
      { name: 'effective_date', label: 'Fecha efectiva', type: 'date' },
      { name: 'obsolete_date', label: 'Fecha obsoleta', type: 'date' },
      {
        name: 'visibility',
        label: 'Visibilidad',
        type: 'select',
        defaultValue: 'shared',
        options: [
          ['shared', 'Compartido Supplier-Customer'],
          ['private', 'Privado interno'],
        ],
      },
    ],
    workflowActions: [
      {
        action: 'approve',
        label: 'Aprobar',
        confirm: '¿Aprobar este documento como vigente?',
        disabledStatuses: {
          effective: 'El documento ya está vigente.',
          obsolete: 'No se puede aprobar un documento obsoleto.',
        },
      },
    ],
  },
  {
    key: 'document-versions',
    label: 'Versiones documentales',
    resource: 'document-versions',
    icon: FileText,
    description: 'Versiones de documentos controlados, archivo, checksum y aprobación.',
    columns: [
      ['document', 'Documento'],
      ['revision', 'Rev.'],
      ['approved_by', 'Aprobado por'],
      ['approved_at', 'Aprobado'],
    ],
    formFields: [
      {
        name: 'document',
        label: 'Documento',
        type: 'relation',
        resource: 'documents',
        required: true,
        optionFields: ['document_number', 'title'],
      },
      { name: 'revision', label: 'Revisión', type: 'text', required: true },
      { name: 'change_reason', label: 'Motivo de cambio', type: 'textarea', required: true },
      { name: 'file', label: 'Archivo', type: 'file', omitWhenEmpty: true },
      { name: 'checksum', label: 'Checksum', type: 'text' },
      { name: 'approved_by', label: 'Aprobado por', type: 'text' },
      { name: 'approved_at', label: 'Fecha aprobación', type: 'datetime-local' },
      {
        name: 'visibility',
        label: 'Visibilidad',
        type: 'select',
        defaultValue: 'shared',
        options: [
          ['shared', 'Compartido Supplier-Customer'],
          ['private', 'Privado interno'],
        ],
      },
    ],
  },
  {
    key: 'rfqs',
    label: 'RFQ',
    resource: 'rfqs',
    icon: FileCheck,
    description: 'Solicitudes de cotización y requisitos asociados.',
    columns: [
      ['rfq_number', 'RFQ'],
      ['title', 'Título'],
      ['status', 'Estado'],
      ['requested_due_date', 'Fecha requerida'],
    ],
    formFields: [
      {
        name: 'account',
        label: 'Cuenta',
        type: 'relation',
        resource: 'accounts',
        required: true,
        optionFields: ['account_code', 'name'],
      },
      { name: 'rfq_number', label: 'Número RFQ', type: 'text', required: true },
      { name: 'title', label: 'Título', type: 'text', required: true },
      {
        name: 'status',
        label: 'Estado',
        type: 'select',
        defaultValue: 'draft',
        options: [
          ['draft', 'Borrador'],
          ['sent', 'Enviada'],
          ['quoted', 'Cotizada'],
          ['closed', 'Cerrada'],
          ['cancelled', 'Cancelada'],
        ],
      },
      { name: 'requested_due_date', label: 'Fecha requerida', type: 'date' },
      {
        name: 'requirements',
        label: 'Requisitos asociados',
        type: 'multirelation',
        resource: 'requirements',
        optionFields: ['requirement_id', 'title'],
      },
      { name: 'notes', label: 'Notas', type: 'textarea' },
      {
        name: 'visibility',
        label: 'Visibilidad',
        type: 'select',
        defaultValue: 'shared',
        options: [
          ['shared', 'Compartido Supplier-Customer'],
          ['private', 'Privado interno'],
        ],
      },
    ],
    workflowActions: [
      {
        action: 'send',
        label: 'Enviar',
        confirm: '¿Marcar esta RFQ como enviada?',
        disabledStatuses: {
          sent: 'La RFQ ya fue enviada.',
          quoted: 'La RFQ ya fue cotizada.',
          closed: 'La RFQ está cerrada.',
          cancelled: 'La RFQ está cancelada.',
        },
      },
    ],
  },
  {
    key: 'quotes',
    label: 'Cotizaciones',
    resource: 'quotes',
    icon: Gauge,
    description: 'Cotizaciones controladas, montos, vigencia y visibilidad privada/comercial.',
    columns: [
      ['quote_number', 'Cotización'],
      ['status', 'Estado'],
      ['currency', 'Moneda'],
      ['total_amount', 'Monto'],
    ],
    formFields: [
      {
        name: 'account',
        label: 'Cuenta',
        type: 'relation',
        resource: 'accounts',
        required: true,
        optionFields: ['account_code', 'name'],
      },
      {
        name: 'rfq',
        label: 'RFQ relacionada',
        type: 'relation',
        resource: 'rfqs',
        optionFields: ['rfq_number', 'title'],
      },
      { name: 'quote_number', label: 'Número cotización', type: 'text', required: true },
      {
        name: 'status',
        label: 'Estado',
        type: 'select',
        defaultValue: 'draft',
        options: [
          ['draft', 'Borrador'],
          ['submitted', 'Presentada'],
          ['approved', 'Aprobada'],
          ['rejected', 'Rechazada'],
          ['expired', 'Expirada'],
        ],
      },
      { name: 'currency', label: 'Moneda', type: 'text', defaultValue: 'USD' },
      { name: 'total_amount', label: 'Monto total', type: 'number', defaultValue: 0, step: '0.01' },
      { name: 'valid_until', label: 'Válida hasta', type: 'date' },
      { name: 'supplier_cost', label: 'Costo interno Supplier', type: 'number', defaultValue: 0, step: '0.01', requiresPermission: 'can_view_private_financials' },
      { name: 'margin', label: 'Margen interno %', type: 'number', defaultValue: 0, step: '0.01', requiresPermission: 'can_view_private_financials' },
      { name: 'commission', label: 'Comisión interna', type: 'number', defaultValue: 0, step: '0.01', requiresPermission: 'can_view_private_financials' },
      { name: 'advance', label: 'Adelanto interno', type: 'number', defaultValue: 0, step: '0.01', requiresPermission: 'can_view_private_financials' },
      { name: 'forecast_probability', label: 'Forecast %', type: 'number', defaultValue: 0, min: 0, max: 100, requiresPermission: 'can_access_supplier_cockpit' },
      { name: 'private_margin_notes', label: 'Notas privadas de margen', type: 'textarea', requiresPermission: 'can_view_private_financials' },
      { name: 'internal_notes', label: 'Notas internas', type: 'textarea', requiresPermission: 'can_access_supplier_cockpit' },
      {
        name: 'visibility',
        label: 'Visibilidad',
        type: 'select',
        defaultValue: 'supplier_private',
        options: medsupplierVisibilityOptions,
      },
    ],
    workflowActions: [
      {
        action: 'approve',
        label: 'Aprobar',
        confirm: '¿Aprobar esta cotización?',
        disabledStatuses: {
          approved: 'La cotización ya está aprobada.',
          rejected: 'La cotización ya fue rechazada.',
          expired: 'La cotización está expirada.',
        },
        disableWhenExpired: true,
        expiredReason: 'No se puede aprobar una cotización expirada.',
      },
      {
        action: 'reject',
        label: 'Rechazar',
        confirm: '¿Rechazar esta cotización?',
        disabledStatuses: {
          approved: 'La cotización ya está aprobada.',
          rejected: 'La cotización ya fue rechazada.',
          expired: 'La cotización está expirada.',
        },
      },
    ],
  },
  {
    key: 'quote-lines',
    label: 'Líneas de cotización',
    resource: 'quote-lines',
    icon: ClipboardList,
    description: 'Detalle técnico y pricing por línea, con separación de precio visible y costo interno.',
    columns: [
      ['line_number', 'Línea'],
      ['product_code', 'Producto'],
      ['quantity', 'Cantidad'],
      ['unit_price', 'Precio'],
    ],
    formFields: [
      { name: 'quote', label: 'Cotización', type: 'relation', resource: 'quotes', required: true, optionFields: ['quote_number'] },
      { name: 'rfq', label: 'RFQ', type: 'relation', resource: 'rfqs', optionFields: ['rfq_number', 'title'] },
      { name: 'account', label: 'Cuenta', type: 'relation', resource: 'accounts', required: true, optionFields: ['account_code', 'name'] },
      { name: 'line_number', label: 'Línea', type: 'number', defaultValue: 1, required: true },
      { name: 'product_code', label: 'Código producto', type: 'text' },
      { name: 'description', label: 'Descripción', type: 'textarea', required: true },
      { name: 'technical_description', label: 'Descripción técnica', type: 'textarea' },
      { name: 'quantity', label: 'Cantidad', type: 'number', defaultValue: 0, step: '0.001' },
      { name: 'uom', label: 'UOM', type: 'text', defaultValue: 'EA' },
      { name: 'moq', label: 'MOQ', type: 'number', defaultValue: 0, step: '0.001' },
      { name: 'lead_time_days', label: 'Lead time días', type: 'number', defaultValue: 0 },
      { name: 'tooling', label: 'Tooling', type: 'text' },
      { name: 'incoterm', label: 'Incoterm', type: 'text' },
      { name: 'unit_price', label: 'Precio unitario', type: 'number', defaultValue: 0, step: '0.0001' },
      { name: 'supplier_cost', label: 'Costo interno', type: 'number', defaultValue: 0, step: '0.0001', requiresPermission: 'can_view_private_financials' },
      { name: 'margin', label: 'Margen %', type: 'number', defaultValue: 0, step: '0.01', requiresPermission: 'can_view_private_financials' },
      { name: 'currency', label: 'Moneda', type: 'text', defaultValue: 'USD' },
      { name: 'valid_until', label: 'Validez', type: 'date' },
      { name: 'taxes_and_charges', label: 'Impuestos/cargos', type: 'number', defaultValue: 0, step: '0.01' },
      { name: 'customer_notes', label: 'Notas visibles cliente', type: 'textarea' },
      { name: 'internal_notes', label: 'Notas internas', type: 'textarea', requiresPermission: 'can_access_supplier_cockpit' },
      { name: 'visibility', label: 'Visibilidad', type: 'select', defaultValue: 'customer_shared', options: medsupplierVisibilityOptions },
    ],
  },
  {
    key: 'orders',
    label: 'Órdenes',
    resource: 'purchase-orders',
    icon: PackageCheck,
    description: 'POs, fechas prometidas, estado operativo y trazabilidad hacia lotes y shipments.',
    columns: [
      ['po_number', 'PO'],
      ['status', 'Estado'],
      ['promised_ship_date', 'Fecha promesa'],
      ['total_amount', 'Monto'],
    ],
    formFields: [
      {
        name: 'account',
        label: 'Cuenta',
        type: 'relation',
        resource: 'accounts',
        required: true,
        optionFields: ['account_code', 'name'],
      },
      {
        name: 'quote',
        label: 'Cotización relacionada',
        type: 'relation',
        resource: 'quotes',
        optionFields: ['quote_number'],
      },
      { name: 'po_number', label: 'Número PO', type: 'text', required: true },
      {
        name: 'status',
        label: 'Estado',
        type: 'select',
        defaultValue: 'received',
        options: [
          ['received', 'Recibida'],
          ['confirmed', 'Confirmada'],
          ['in_production', 'En producción'],
          ['shipped', 'Enviada'],
          ['closed', 'Cerrada'],
          ['cancelled', 'Cancelada'],
        ],
      },
      { name: 'customer_po_date', label: 'Fecha PO cliente', type: 'date' },
      { name: 'promised_ship_date', label: 'Fecha promesa', type: 'date' },
      { name: 'currency', label: 'Moneda', type: 'text', defaultValue: 'USD' },
      { name: 'total_amount', label: 'Monto total', type: 'number', defaultValue: 0, step: '0.01' },
      {
        name: 'visibility',
        label: 'Visibilidad',
        type: 'select',
        defaultValue: 'shared',
        options: [
          ['shared', 'Compartido Supplier-Customer'],
          ['private', 'Privado interno'],
        ],
      },
    ],
    workflowActions: [
      {
        action: 'close',
        label: 'Cerrar',
        confirm: '¿Cerrar esta orden de compra?',
        disabledStatuses: {
          closed: 'La orden ya está cerrada.',
          cancelled: 'La orden está cancelada.',
        },
      },
    ],
  },
  {
    key: 'order-lines',
    label: 'Líneas de orden',
    resource: 'order-lines',
    icon: PackageCheck,
    description: 'Backlog, cantidades entregadas/pendientes y estado por línea de PO.',
    columns: [
      ['line_number', 'Línea'],
      ['product_code', 'Producto'],
      ['status', 'Estado'],
      ['pending_quantity', 'Pendiente'],
    ],
    formFields: [
      { name: 'purchase_order', label: 'PO', type: 'relation', resource: 'purchase-orders', required: true, optionFields: ['po_number'] },
      { name: 'quote_line', label: 'Línea cotización', type: 'relation', resource: 'quote-lines', optionFields: ['line_number', 'product_code'] },
      { name: 'account', label: 'Cuenta', type: 'relation', resource: 'accounts', required: true, optionFields: ['account_code', 'name'] },
      { name: 'line_number', label: 'Línea', type: 'number', defaultValue: 1, required: true },
      { name: 'product_code', label: 'Código producto', type: 'text' },
      { name: 'description', label: 'Descripción', type: 'textarea', required: true },
      { name: 'quantity', label: 'Cantidad', type: 'number', defaultValue: 0, step: '0.001' },
      { name: 'delivered_quantity', label: 'Entregado', type: 'number', defaultValue: 0, step: '0.001' },
      { name: 'pending_quantity', label: 'Pendiente', type: 'number', defaultValue: 0, step: '0.001' },
      { name: 'uom', label: 'UOM', type: 'text', defaultValue: 'EA' },
      { name: 'due_date', label: 'Vence', type: 'date' },
      { name: 'status', label: 'Estado', type: 'select', defaultValue: 'open', options: [['open', 'Abierta'], ['confirmed', 'Confirmada'], ['partial', 'Parcial'], ['delivered', 'Entregada'], ['closed', 'Cerrada'], ['cancelled', 'Cancelada']] },
      { name: 'discrepancy_notes', label: 'Discrepancias', type: 'textarea' },
      { name: 'visibility', label: 'Visibilidad', type: 'select', defaultValue: 'customer_shared', options: medsupplierVisibilityOptions },
    ],
  },
  {
    key: 'lots',
    label: 'Lotes',
    resource: 'lots',
    icon: PackageCheck,
    description: 'Lotes de producto, cantidades, unidad de medida, manufactura y expiración.',
    columns: [
      ['lot_number', 'Lote'],
      ['product_code', 'Producto'],
      ['quantity', 'Cantidad'],
      ['uom', 'UOM'],
    ],
    formFields: [
      {
        name: 'account',
        label: 'Cuenta',
        type: 'relation',
        resource: 'accounts',
        required: true,
        optionFields: ['account_code', 'name'],
      },
      {
        name: 'purchase_order',
        label: 'PO relacionada',
        type: 'relation',
        resource: 'purchase-orders',
        optionFields: ['po_number'],
      },
      { name: 'lot_number', label: 'Número de lote', type: 'text', required: true },
      { name: 'product_code', label: 'Código producto', type: 'text', required: true },
      { name: 'product_description', label: 'Descripción producto', type: 'text' },
      { name: 'quantity', label: 'Cantidad', type: 'number', defaultValue: 0, step: '0.001' },
      { name: 'uom', label: 'Unidad', type: 'text', defaultValue: 'EA' },
      { name: 'manufactured_at', label: 'Fecha manufactura', type: 'date' },
      { name: 'expiration_at', label: 'Fecha expiración', type: 'date' },
      {
        name: 'visibility',
        label: 'Visibilidad',
        type: 'select',
        defaultValue: 'shared',
        options: [
          ['shared', 'Compartido Supplier-Customer'],
          ['private', 'Privado interno'],
        ],
      },
    ],
  },
  {
    key: 'shipments',
    label: 'Shipments',
    resource: 'shipments',
    icon: Truck,
    description: 'Entregas, tracking, carrier y estado logístico compartido.',
    columns: [
      ['shipment_number', 'Shipment'],
      ['status', 'Estado'],
      ['carrier', 'Carrier'],
      ['tracking_number', 'Tracking'],
    ],
    formFields: [
      {
        name: 'account',
        label: 'Cuenta',
        type: 'relation',
        resource: 'accounts',
        required: true,
        optionFields: ['account_code', 'name'],
      },
      {
        name: 'purchase_order',
        label: 'PO relacionada',
        type: 'relation',
        resource: 'purchase-orders',
        optionFields: ['po_number'],
      },
      { name: 'shipment_number', label: 'Número shipment', type: 'text', required: true },
      {
        name: 'status',
        label: 'Estado',
        type: 'select',
        defaultValue: 'planned',
        options: [
          ['planned', 'Planificado'],
          ['in_transit', 'En tránsito'],
          ['delivered', 'Entregado'],
          ['delayed', 'Retrasado'],
          ['cancelled', 'Cancelado'],
        ],
      },
      { name: 'carrier', label: 'Carrier', type: 'text' },
      { name: 'tracking_number', label: 'Tracking', type: 'text' },
      { name: 'shipped_at', label: 'Fecha envío', type: 'datetime-local' },
      { name: 'delivered_at', label: 'Fecha entrega', type: 'datetime-local' },
      {
        name: 'visibility',
        label: 'Visibilidad',
        type: 'select',
        defaultValue: 'shared',
        options: [
          ['shared', 'Compartido Supplier-Customer'],
          ['private', 'Privado interno'],
        ],
      },
    ],
  },
  {
    key: 'shipment-milestones',
    label: 'Milestones shipment',
    resource: 'shipment-milestones',
    icon: Truck,
    description: 'ASN, POD, tracking, incidentes, fechas esperadas/reales y retrasos.',
    columns: [
      ['milestone_type', 'Milestone'],
      ['status', 'Estado'],
      ['expected_at', 'Esperado'],
      ['actual_at', 'Real'],
    ],
    formFields: [
      { name: 'shipment', label: 'Shipment', type: 'relation', resource: 'shipments', required: true, optionFields: ['shipment_number'] },
      { name: 'account', label: 'Cuenta', type: 'relation', resource: 'accounts', required: true, optionFields: ['account_code', 'name'] },
      { name: 'milestone_type', label: 'Tipo milestone', type: 'text', required: true },
      { name: 'status', label: 'Estado', type: 'select', defaultValue: 'planned', options: [['planned', 'Planificado'], ['completed', 'Completado'], ['delayed', 'Retrasado'], ['cancelled', 'Cancelado']] },
      { name: 'expected_at', label: 'Fecha esperada', type: 'datetime-local' },
      { name: 'actual_at', label: 'Fecha real', type: 'datetime-local' },
      { name: 'carrier', label: 'Carrier', type: 'text' },
      { name: 'tracking_number', label: 'Tracking', type: 'text' },
      { name: 'incident_notes', label: 'Incidentes', type: 'textarea' },
      { name: 'delay_reason', label: 'Razón retraso', type: 'textarea' },
      { name: 'visibility', label: 'Visibilidad', type: 'select', defaultValue: 'customer_shared', options: medsupplierVisibilityOptions },
    ],
  },
  {
    key: 'inspections',
    label: 'Inspecciones',
    resource: 'inspections',
    icon: ClipboardCheck,
    description: 'Inspecciones de recepción, resultado, responsable y hallazgos.',
    columns: [
      ['inspection_number', 'Inspección'],
      ['result', 'Resultado'],
      ['inspected_by', 'Inspector'],
      ['received_at', 'Recepción'],
    ],
    formFields: [
      {
        name: 'account',
        label: 'Cuenta',
        type: 'relation',
        resource: 'accounts',
        required: true,
        optionFields: ['account_code', 'name'],
      },
      {
        name: 'shipment',
        label: 'Shipment relacionado',
        type: 'relation',
        resource: 'shipments',
        optionFields: ['shipment_number'],
      },
      { name: 'inspection_number', label: 'Número inspección', type: 'text', required: true },
      { name: 'received_at', label: 'Fecha recepción', type: 'datetime-local' },
      {
        name: 'result',
        label: 'Resultado',
        type: 'select',
        defaultValue: 'pending',
        options: [
          ['pending', 'Pendiente'],
          ['accepted', 'Aceptado'],
          ['accepted_with_deviation', 'Aceptado con desviación'],
          ['rejected', 'Rechazado'],
        ],
      },
      { name: 'inspected_by', label: 'Inspeccionado por', type: 'text' },
      { name: 'findings', label: 'Hallazgos', type: 'textarea' },
      {
        name: 'visibility',
        label: 'Visibilidad',
        type: 'select',
        defaultValue: 'shared',
        options: [
          ['shared', 'Compartido Supplier-Customer'],
          ['private', 'Privado interno'],
        ],
      },
    ],
  },
  {
    key: 'quality',
    label: 'Calidad',
    resource: 'quality-events',
    icon: AlertTriangle,
    description: 'NCR, quejas, desviaciones y hallazgos conectados a inspecciones y CAPA.',
    columns: [
      ['event_number', 'Evento'],
      ['event_type', 'Tipo'],
      ['severity', 'Severidad'],
      ['status', 'Estado'],
    ],
    formFields: [
      {
        name: 'account',
        label: 'Cuenta',
        type: 'relation',
        resource: 'accounts',
        required: true,
        optionFields: ['account_code', 'name'],
      },
      {
        name: 'inspection',
        label: 'Inspección relacionada',
        type: 'relation',
        resource: 'inspections',
        optionFields: ['inspection_number'],
      },
      { name: 'event_number', label: 'Número evento', type: 'text', required: true },
      {
        name: 'event_type',
        label: 'Tipo',
        type: 'select',
        defaultValue: 'ncr',
        options: [
          ['ncr', 'NCR'],
          ['complaint', 'Queja'],
          ['deviation', 'Desviación'],
          ['audit_finding', 'Hallazgo de auditoría'],
        ],
      },
      { name: 'severity', label: 'Severidad', type: 'text', defaultValue: 'medium' },
      {
        name: 'status',
        label: 'Estado',
        type: 'select',
        defaultValue: 'open',
        options: [
          ['open', 'Abierto'],
          ['triage', 'Triage'],
          ['investigation', 'Investigación'],
          ['capa_required', 'CAPA requerida'],
          ['closed', 'Cerrado'],
        ],
      },
      { name: 'title', label: 'Título', type: 'text', required: true },
      { name: 'description', label: 'Descripción', type: 'textarea', required: true },
      { name: 'reported_at', label: 'Fecha reporte', type: 'datetime-local', omitWhenEmpty: true },
      { name: 'owner', label: 'Responsable', type: 'text' },
      {
        name: 'visibility',
        label: 'Visibilidad',
        type: 'select',
        defaultValue: 'shared',
        options: [
          ['shared', 'Compartido Supplier-Customer'],
          ['private', 'Privado interno'],
        ],
      },
    ],
    workflowActions: [
      {
        action: 'close',
        label: 'Cerrar',
        confirm: '¿Cerrar este evento de calidad?',
        disabledStatuses: {
          closed: 'El evento ya está cerrado.',
        },
      },
    ],
  },
  {
    key: 'capas',
    label: 'CAPA',
    resource: 'capas',
    icon: ShieldCheck,
    description: 'CAPA básica, causa raíz, acciones correctivas/preventivas y verificación de efectividad.',
    columns: [
      ['capa_number', 'CAPA'],
      ['status', 'Estado'],
      ['owner', 'Responsable'],
      ['due_date', 'Vence'],
    ],
    formFields: [
      {
        name: 'account',
        label: 'Cuenta',
        type: 'relation',
        resource: 'accounts',
        required: true,
        optionFields: ['account_code', 'name'],
      },
      {
        name: 'quality_event',
        label: 'Evento de calidad',
        type: 'relation',
        resource: 'quality-events',
        optionFields: ['event_number', 'title'],
      },
      { name: 'capa_number', label: 'Número CAPA', type: 'text', required: true },
      {
        name: 'status',
        label: 'Estado',
        type: 'select',
        defaultValue: 'draft',
        options: [
          ['draft', 'Borrador'],
          ['open', 'Abierta'],
          ['effectiveness_check', 'Verificación de efectividad'],
          ['closed', 'Cerrada'],
          ['cancelled', 'Cancelada'],
        ],
      },
      { name: 'root_cause', label: 'Causa raíz', type: 'textarea' },
      { name: 'corrective_action', label: 'Acción correctiva', type: 'textarea' },
      { name: 'preventive_action', label: 'Acción preventiva', type: 'textarea' },
      { name: 'owner', label: 'Responsable', type: 'text' },
      { name: 'due_date', label: 'Fecha vencimiento', type: 'date' },
      { name: 'effectiveness_result', label: 'Resultado de efectividad', type: 'textarea' },
      {
        name: 'visibility',
        label: 'Visibilidad',
        type: 'select',
        defaultValue: 'shared',
        options: [
          ['shared', 'Compartido Supplier-Customer'],
          ['private', 'Privado interno'],
        ],
      },
    ],
    workflowActions: [
      {
        action: 'close',
        label: 'Cerrar',
        confirm: '¿Cerrar esta CAPA?',
        disabledStatuses: {
          closed: 'La CAPA ya está cerrada.',
          cancelled: 'La CAPA está cancelada.',
        },
        requiredField: 'effectiveness_result',
        requiredFieldReason: 'Se requiere resultado de efectividad.',
      },
    ],
  },
  {
    key: 'scorecards',
    label: 'Scorecards',
    resource: 'scorecards',
    icon: Gauge,
    description: 'Desempeño de calidad, entrega, respuesta y QBR.',
    columns: [
      ['period_start', 'Desde'],
      ['period_end', 'Hasta'],
      ['overall_score', 'Score'],
      ['visibility', 'Visibilidad'],
    ],
    formFields: [
      {
        name: 'account',
        label: 'Cuenta',
        type: 'relation',
        resource: 'accounts',
        required: true,
        optionFields: ['account_code', 'name'],
      },
      { name: 'period_start', label: 'Inicio periodo', type: 'date', required: true },
      { name: 'period_end', label: 'Fin periodo', type: 'date', required: true },
      { name: 'quality_score', label: 'Score calidad', type: 'number', defaultValue: 0, step: '0.01' },
      { name: 'delivery_score', label: 'Score entrega', type: 'number', defaultValue: 0, step: '0.01' },
      { name: 'responsiveness_score', label: 'Score respuesta', type: 'number', defaultValue: 0, step: '0.01' },
      { name: 'overall_score', label: 'Score total', type: 'number', defaultValue: 0, step: '0.01' },
      { name: 'qbr_notes', label: 'Notas QBR', type: 'textarea' },
      {
        name: 'visibility',
        label: 'Visibilidad',
        type: 'select',
        defaultValue: 'shared',
        options: [
          ['shared', 'Compartido Supplier-Customer'],
          ['private', 'Privado interno'],
        ],
      },
    ],
  },
  {
    key: 'fmeas',
    label: 'FMEA',
    resource: 'fmeas',
    icon: ShieldCheck,
    description: 'FMEA básico ISO 14971-ready para soportar gestión de riesgo, mitigaciones y revisión.',
    columns: [
      ['fmea_number', 'FMEA'],
      ['title', 'Título'],
      ['status', 'Estado'],
      ['review_due_date', 'Revisión'],
    ],
    formFields: [
      { name: 'account', label: 'Cuenta', type: 'relation', resource: 'accounts', required: true, optionFields: ['account_code', 'name'] },
      { name: 'fmea_number', label: 'Número FMEA', type: 'text', required: true },
      { name: 'title', label: 'Título', type: 'text', required: true },
      { name: 'process', label: 'Proceso', type: 'text' },
      { name: 'status', label: 'Estado', type: 'select', defaultValue: 'draft', options: [['draft', 'Borrador'], ['active', 'Activo'], ['under_review', 'En revisión'], ['closed', 'Cerrado'], ['obsolete', 'Obsoleto']] },
      { name: 'owner', label: 'Responsable', type: 'text' },
      { name: 'review_due_date', label: 'Próxima revisión', type: 'date' },
      { name: 'notes', label: 'Notas', type: 'textarea' },
      { name: 'visibility', label: 'Visibilidad', type: 'select', defaultValue: 'customer_shared', options: medsupplierVisibilityOptions },
    ],
  },
  {
    key: 'fmea-items',
    label: 'FMEA items',
    resource: 'fmea-items',
    icon: AlertTriangle,
    description: 'Hazards/failure modes, causa, efecto, S/O/D, risk score, mitigación y riesgo residual.',
    columns: [
      ['failure_mode', 'Failure mode'],
      ['severity', 'S'],
      ['occurrence', 'O'],
      ['risk_score', 'Score'],
    ],
    formFields: [
      { name: 'fmea', label: 'FMEA', type: 'relation', resource: 'fmeas', required: true, optionFields: ['fmea_number', 'title'] },
      { name: 'account', label: 'Cuenta', type: 'relation', resource: 'accounts', required: true, optionFields: ['account_code', 'name'] },
      { name: 'quality_event', label: 'Evento calidad', type: 'relation', resource: 'quality-events', optionFields: ['event_number', 'title'] },
      { name: 'capa', label: 'CAPA', type: 'relation', resource: 'capas', optionFields: ['capa_number'] },
      { name: 'document', label: 'Documento', type: 'relation', resource: 'documents', optionFields: ['document_number', 'title'] },
      { name: 'hazard', label: 'Hazard', type: 'text', required: true },
      { name: 'failure_mode', label: 'Failure mode', type: 'text', required: true },
      { name: 'cause', label: 'Causa', type: 'textarea' },
      { name: 'effect', label: 'Efecto', type: 'textarea' },
      { name: 'severity', label: 'Severity', type: 'number', defaultValue: 1, min: 1, max: 10 },
      { name: 'occurrence', label: 'Occurrence', type: 'number', defaultValue: 1, min: 1, max: 10 },
      { name: 'detection', label: 'Detection', type: 'number', defaultValue: 1, min: 1, max: 10 },
      { name: 'mitigation', label: 'Mitigación', type: 'textarea' },
      { name: 'owner', label: 'Responsable', type: 'text' },
      { name: 'due_date', label: 'Vence', type: 'date' },
      { name: 'residual_risk', label: 'Riesgo residual', type: 'textarea' },
      { name: 'status', label: 'Estado', type: 'select', defaultValue: 'open', options: [['open', 'Abierto'], ['mitigating', 'En mitigación'], ['accepted', 'Aceptado'], ['closed', 'Cerrado']] },
      { name: 'visibility', label: 'Visibilidad', type: 'select', defaultValue: 'customer_shared', options: medsupplierVisibilityOptions },
    ],
  },
  {
    key: 'evidence-packages',
    label: 'Evidence packages',
    resource: 'evidence-packages',
    icon: FileCheck,
    description: 'Paquetes audit-ready con metadata, objetos incluidos, checksum y export JSON/CSV MVP.',
    columns: [
      ['package_number', 'Paquete'],
      ['title', 'Título'],
      ['status', 'Estado'],
      ['checksum', 'Checksum'],
    ],
    formFields: [
      { name: 'account', label: 'Cuenta', type: 'relation', resource: 'accounts', required: true, optionFields: ['account_code', 'name'] },
      { name: 'package_number', label: 'Número paquete', type: 'text', required: true },
      { name: 'title', label: 'Título', type: 'text', required: true },
      { name: 'scope', label: 'Scope', type: 'text' },
      { name: 'date_from', label: 'Desde', type: 'date' },
      { name: 'date_to', label: 'Hasta', type: 'date' },
      { name: 'version', label: 'Versión', type: 'text', defaultValue: '1.0' },
      { name: 'status', label: 'Estado', type: 'select', defaultValue: 'draft', options: [['draft', 'Borrador'], ['prepared', 'Preparado'], ['approved', 'Aprobado'], ['exported', 'Exportado'], ['archived', 'Archivado']] },
      { name: 'export_format', label: 'Formato export', type: 'select', defaultValue: 'json', options: [['json', 'JSON'], ['csv', 'CSV']] },
      { name: 'visibility', label: 'Visibilidad', type: 'select', defaultValue: 'regulated_evidence', options: medsupplierVisibilityOptions },
    ],
    workflowActions: [
      { action: 'prepare', label: 'Preparar', confirm: '¿Preparar paquete de evidencia?' },
      { action: 'approve', label: 'Aprobar', confirm: '¿Aprobar paquete de evidencia?' },
    ],
  },
  {
    key: 'evidence-package-entries',
    label: 'Evidence entries',
    resource: 'evidence-package-entries',
    icon: ClipboardList,
    description: 'Objetos incluidos en paquetes de evidencia audit-ready.',
    columns: [
      ['object_type', 'Objeto'],
      ['object_id', 'ID'],
      ['label', 'Etiqueta'],
      ['added_at', 'Agregado'],
    ],
    formFields: [
      { name: 'package', label: 'Paquete', type: 'relation', resource: 'evidence-packages', required: true, optionFields: ['package_number', 'title'] },
      { name: 'object_type', label: 'Tipo objeto', type: 'text', required: true },
      { name: 'object_id', label: 'ID objeto', type: 'text', required: true },
      { name: 'label', label: 'Etiqueta', type: 'text' },
    ],
  },
  {
    key: 'audit',
    label: 'Audit Trail',
    resource: 'audit-events',
    icon: History,
    description: 'Eventos auditables exportables del módulo MedSupplier.',
    columns: [
      ['created_at', 'Fecha'],
      ['action', 'Acción'],
      ['record_type', 'Registro'],
      ['description', 'Descripción'],
    ],
  },
  {
    key: 'integration',
    label: 'Integración',
    resource: null,
    icon: Link2,
    description: 'AdminApps gobierna organizaciones, usuarios, roles, licencias y habilitación del producto MEDSUPPLIER.',
    columns: [],
  },
];

export const getMedSupplierSection = (key) => (
  medsupplierSections.find((section) => section.key === key) || medsupplierSections[0]
);
