# Generated by Django 6.0.6 on 2026-06-27 02:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_featureflag_id'),
        ('medsupplier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidencePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('public_shared', 'Compartido público controlado'), ('customer_shared', 'Compartido con cliente'), ('supplier_private', 'Privado Supplier'), ('supplier_confidential', 'Confidencial Supplier'), ('regulated_evidence', 'Evidencia regulada'), ('audit_only', 'Solo auditoría'), ('archived', 'Archivado'), ('obsolete', 'Obsoleto'), ('shared', 'Legacy compartido'), ('private', 'Legacy privado')], default='shared', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_number', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('scope', models.CharField(blank=True, max_length=120)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('version', models.CharField(default='1.0', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('prepared', 'Preparado'), ('approved', 'Aprobado'), ('exported', 'Exportado'), ('archived', 'Archivado')], default='draft', max_length=30)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('export_format', models.CharField(default='json', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'medsupplier_evidence_packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidencePackageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=120)),
                ('object_id', models.CharField(max_length=120)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medsupplier_evidence_package_entries',
                'ordering': ['object_type', 'object_id'],
            },
        ),
        migrations.CreateModel(
            name='MedSupplierESignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(choices=[('approval', 'Aprobación'), ('review', 'Revisión'), ('closure', 'Cierre'), ('status_change', 'Cambio de estado'), ('export_approval', 'Aprobación de exportación')], max_length=40)),
                ('reason', models.TextField()),
                ('object_type', models.CharField(max_length=120)),
                ('object_id', models.CharField(max_length=120)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('signature_hash', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medsupplier_esignatures',
                'ordering': ['-signed_at'],
            },
        ),
        migrations.CreateModel(
            name='MedSupplierUserScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('supplier', 'Supplier'), ('customer', 'Customer')], max_length=20)),
                ('role', models.CharField(choices=[('supplier_admin', 'Supplier Admin'), ('supplier_sales', 'Supplier Sales'), ('supplier_finance', 'Supplier Finance'), ('supplier_quality', 'Supplier Quality'), ('supplier_logistics', 'Supplier Logistics'), ('supplier_viewer', 'Supplier Viewer'), ('customer_admin', 'Customer Admin'), ('customer_buyer', 'Customer Buyer / Procurement'), ('customer_quality', 'Customer Quality'), ('customer_logistics', 'Customer Logistics'), ('customer_auditor', 'Customer Auditor'), ('customer_viewer', 'Customer Viewer')], max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medsupplier_user_scopes',
                'ordering': ['organization', 'side', 'role'],
            },
        ),
        migrations.CreateModel(
            name='SupplierFMEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('public_shared', 'Compartido público controlado'), ('customer_shared', 'Compartido con cliente'), ('supplier_private', 'Privado Supplier'), ('supplier_confidential', 'Confidencial Supplier'), ('regulated_evidence', 'Evidencia regulada'), ('audit_only', 'Solo auditoría'), ('archived', 'Archivado'), ('obsolete', 'Obsoleto'), ('shared', 'Legacy compartido'), ('private', 'Legacy privado')], default='shared', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fmea_number', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('process', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('under_review', 'En revisión'), ('closed', 'Cerrado'), ('obsolete', 'Obsoleto')], default='draft', max_length=30)),
                ('owner', models.CharField(blank=True, max_length=150)),
                ('review_due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'medsupplier_fmeas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierFMEAItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('public_shared', 'Compartido público controlado'), ('customer_shared', 'Compartido con cliente'), ('supplier_private', 'Privado Supplier'), ('supplier_confidential', 'Confidencial Supplier'), ('regulated_evidence', 'Evidencia regulada'), ('audit_only', 'Solo auditoría'), ('archived', 'Archivado'), ('obsolete', 'Obsoleto'), ('shared', 'Legacy compartido'), ('private', 'Legacy privado')], default='shared', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hazard', models.CharField(max_length=255)),
                ('failure_mode', models.CharField(max_length=255)),
                ('cause', models.TextField(blank=True)),
                ('effect', models.TextField(blank=True)),
                ('severity', models.PositiveSmallIntegerField(default=1)),
                ('occurrence', models.PositiveSmallIntegerField(default=1)),
                ('detection', models.PositiveSmallIntegerField(default=1)),
                ('risk_score', models.PositiveIntegerField(default=1)),
                ('mitigation', models.TextField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=150)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('residual_risk', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('mitigating', 'En mitigación'), ('accepted', 'Aceptado'), ('closed', 'Cerrado')], default='open', max_length=30)),
            ],
            options={
                'db_table': 'medsupplier_fmea_items',
                'ordering': ['-risk_score', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('public_shared', 'Compartido público controlado'), ('customer_shared', 'Compartido con cliente'), ('supplier_private', 'Privado Supplier'), ('supplier_confidential', 'Confidencial Supplier'), ('regulated_evidence', 'Evidencia regulada'), ('audit_only', 'Solo auditoría'), ('archived', 'Archivado'), ('obsolete', 'Obsoleto'), ('shared', 'Legacy compartido'), ('private', 'Legacy privado')], default='shared', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('product_code', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('delivered_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('pending_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('uom', models.CharField(default='EA', max_length=30)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('confirmed', 'Confirmada'), ('partial', 'Parcial'), ('delivered', 'Entregada'), ('closed', 'Cerrada'), ('cancelled', 'Cancelada')], default='open', max_length=30)),
                ('discrepancy_notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'medsupplier_order_lines',
                'ordering': ['purchase_order', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='SupplierQuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('public_shared', 'Compartido público controlado'), ('customer_shared', 'Compartido con cliente'), ('supplier_private', 'Privado Supplier'), ('supplier_confidential', 'Confidencial Supplier'), ('regulated_evidence', 'Evidencia regulada'), ('audit_only', 'Solo auditoría'), ('archived', 'Archivado'), ('obsolete', 'Obsoleto'), ('shared', 'Legacy compartido'), ('private', 'Legacy privado')], default='shared', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('product_code', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('technical_description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('uom', models.CharField(default='EA', max_length=30)),
                ('moq', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('lead_time_days', models.PositiveIntegerField(default=0)),
                ('tooling', models.CharField(blank=True, max_length=180)),
                ('incoterm', models.CharField(blank=True, max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('supplier_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('taxes_and_charges', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('customer_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'medsupplier_quote_lines',
                'ordering': ['quote', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='SupplierShipmentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('public_shared', 'Compartido público controlado'), ('customer_shared', 'Compartido con cliente'), ('supplier_private', 'Privado Supplier'), ('supplier_confidential', 'Confidencial Supplier'), ('regulated_evidence', 'Evidencia regulada'), ('audit_only', 'Solo auditoría'), ('archived', 'Archivado'), ('obsolete', 'Obsoleto'), ('shared', 'Legacy compartido'), ('private', 'Legacy privado')], default='shared', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone_type', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('planned', 'Planificado'), ('completed', 'Completado'), ('delayed', 'Retrasado'), ('cancelled', 'Cancelado')], default='planned', max_length=30)),
                ('expected_at', models.DateTimeField(blank=True, null=True)),
                ('actual_at', models.DateTimeField(blank=True, null=True)),
                ('carrier', models.CharField(blank=True, max_length=120)),
                ('tracking_number', models.CharField(blank=True, max_length=120)),
                ('incident_notes', models.TextField(blank=True)),
                ('delay_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'medsupplier_shipment_milestones',
                'ordering': ['shipment', 'expected_at', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='medsupplierauditevent',
            name='correlation_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='medsupplierauditevent',
            name='event_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='medsupplierauditevent',
            name='exportable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medsupplierauditevent',
            name='object_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='medsupplierauditevent',
            name='object_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='medsupplierauditevent',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='suppliercapa',
            name='evidence_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplierdocument',
            name='major_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='supplierdocument',
            name='minor_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplierdocument',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='advance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='forecast_probability',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='supplier_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='suppliershipment',
            name='asn_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='suppliershipment',
            name='delay_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='suppliershipment',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliershipment',
            name='is_partial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suppliershipment',
            name='pod_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='supplieraccount',
            name='visibility',
            field=models.CharField(choices=[('public_shared', 'Compartido público controlado'), ('customer_shared', 'Compartido con cliente'), ('supplier_private', 'Privado Supplier'), ('supplier_confidential', 'Confidencial Supplier'), ('regulated_evidence', 'Evidencia regulada'), ('audit_only', 'Solo auditoría'), ('archived', 'Archivado'), ('obsolete', 'Obsoleto'), ('shared', 'Legacy compartido'), ('private', 'Legacy privado')], default='shared', max_length=30),
        ),
        migrations.AlterField(
            model_name='supplieraction',
            name='visibility',
            field=models.CharField(choices=[('public_shared', 'Compartido público controlado'), ('customer_shared', 'Compartido con cliente'), ('supplier_private', 'Privado Supplier'), ('supplier_confidential', 'Confidencial Supplier'), ('regulated_evidence', 'Evidencia regulada'), ('audit_only', 'Solo auditoría'), ('archived', 'Archivado'), ('obsolete', 'Obsoleto'), ('shared', 'Legacy compartido'), ('private', 'Legacy privado')], default='shared', max_length=30),
        ),
        migrations.AlterField(
            model_name='suppliercapa',
            name='visibility',
            field=models.CharField(choices=[('public_shared', 'Compartido público controlado'), ('customer_shared', 'Compartido con cliente'), ('supplier_private', 'Privado Supplier'), ('supplier_confidential', 'Confidencial Supplier'), ('regulated_evidence', 'Evidencia regulada'), ('audit_only', 'Solo auditoría'), ('archived', 'Archivado'), ('obsolete', 'Obsoleto'), ('shared', 'Legacy compartido'), ('private', 'Legacy privado')], default='shared', max_length=30),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='visibility',
            field=models.CharField(choices=[('public_shared', 'Compartido público controlado'), ('customer_shared', 'Compartido con cliente'), ('supplier_private', 'Privado Supplier'), ('supplier_confidential', 'Confidencial Supplier'), ('regulated_evidence', 'Evidencia regulada'), ('audit_only', 'Solo auditoría'), ('archived', 'Archivado'), ('obsolete', 'Obsoleto'), ('shared', 'Legacy compartido'), ('private', 'Legacy privado')], default='shared', max_length=30),
        ),
        migrations.AlterField(
            model_name='supplierdocument',
            name='visibility',
            field=models.CharField(choices=[('public_shared', 'Compartido público controlado'), ('customer_shared', 'Compartido con cliente'), ('supplier_private', 'Privado Supplier'), ('supplier_confidential', 'Confidencial Supplier'), ('regulated_evidence', 'Evidencia regulada'), ('audit_only', 'Solo auditoría'), ('archived', 'Archivado'), ('obsolete', 'Obsoleto'), ('shared', 'Legacy compartido'), ('private', 'Legacy privado')], default='shared', max_length=30),
        ),
        migrations.AlterField(
            model_name='supplierdocumentversion',
            name='visibility',
            field=models.CharField(choices=[('public_shared', 'Compartido público controlado'), ('customer_shared', 'Compartido con cliente'), ('supplier_private', 'Privado Supplier'), ('supplier_confidential', 'Confidencial Supplier'), ('regulated_evidence', 'Evidencia regulada'), ('audit_only', 'Solo auditoría'), ('archived', 'Archivado'), ('obsolete', 'Obsoleto'), ('shared', 'Legacy compartido'), ('private', 'Legacy privado')], default='shared', max_length=30),
        ),
        migrations.AlterField(
            model_name='supplierinspection',
            name='visibility',
            field=models.CharField(choices=[('public_shared', 'Compartido público controlado'), ('customer_shared', 'Compartido con cliente'), ('supplier_private', 'Privado Supplier'), ('supplier_confidential', 'Confidencial Supplier'), ('regulated_evidence', 'Evidencia regulada'), ('audit_only', 'Solo auditoría'), ('archived', 'Archivado'), ('obsolete', 'Obsoleto'), ('shared', 'Legacy compartido'), ('private', 'Legacy privado')], default='shared', max_length=30),
        ),
        migrations.AlterField(
            model_name='supplierlot',
            name='visibility',
            field=models.CharField(choices=[('public_shared', 'Compartido público controlado'), ('customer_shared', 'Compartido con cliente'), ('supplier_private', 'Privado Supplier'), ('supplier_confidential', 'Confidencial Supplier'), ('regulated_evidence', 'Evidencia regulada'), ('audit_only', 'Solo auditoría'), ('archived', 'Archivado'), ('obsolete', 'Obsoleto'), ('shared', 'Legacy compartido'), ('private', 'Legacy privado')], default='shared', max_length=30),
        ),
        migrations.AlterField(
            model_name='suppliermeeting',
            name='visibility',
            field=models.CharField(choices=[('public_shared', 'Compartido público controlado'), ('customer_shared', 'Compartido con cliente'), ('supplier_private', 'Privado Supplier'), ('supplier_confidential', 'Confidencial Supplier'), ('regulated_evidence', 'Evidencia regulada'), ('audit_only', 'Solo auditoría'), ('archived', 'Archivado'), ('obsolete', 'Obsoleto'), ('shared', 'Legacy compartido'), ('private', 'Legacy privado')], default='shared', max_length=30),
        ),
        migrations.AlterField(
            model_name='supplierpurchaseorder',
            name='visibility',
            field=models.CharField(choices=[('public_shared', 'Compartido público controlado'), ('customer_shared', 'Compartido con cliente'), ('supplier_private', 'Privado Supplier'), ('supplier_confidential', 'Confidencial Supplier'), ('regulated_evidence', 'Evidencia regulada'), ('audit_only', 'Solo auditoría'), ('archived', 'Archivado'), ('obsolete', 'Obsoleto'), ('shared', 'Legacy compartido'), ('private', 'Legacy privado')], default='shared', max_length=30),
        ),
        migrations.AlterField(
            model_name='supplierqualityevent',
            name='visibility',
            field=models.CharField(choices=[('public_shared', 'Compartido público controlado'), ('customer_shared', 'Compartido con cliente'), ('supplier_private', 'Privado Supplier'), ('supplier_confidential', 'Confidencial Supplier'), ('regulated_evidence', 'Evidencia regulada'), ('audit_only', 'Solo auditoría'), ('archived', 'Archivado'), ('obsolete', 'Obsoleto'), ('shared', 'Legacy compartido'), ('private', 'Legacy privado')], default='shared', max_length=30),
        ),
        migrations.AlterField(
            model_name='supplierquote',
            name='visibility',
            field=models.CharField(choices=[('public_shared', 'Compartido público controlado'), ('customer_shared', 'Compartido con cliente'), ('supplier_private', 'Privado Supplier'), ('supplier_confidential', 'Confidencial Supplier'), ('regulated_evidence', 'Evidencia regulada'), ('audit_only', 'Solo auditoría'), ('archived', 'Archivado'), ('obsolete', 'Obsoleto'), ('shared', 'Legacy compartido'), ('private', 'Legacy privado')], default='shared', max_length=30),
        ),
        migrations.AlterField(
            model_name='supplierrequirement',
            name='visibility',
            field=models.CharField(choices=[('public_shared', 'Compartido público controlado'), ('customer_shared', 'Compartido con cliente'), ('supplier_private', 'Privado Supplier'), ('supplier_confidential', 'Confidencial Supplier'), ('regulated_evidence', 'Evidencia regulada'), ('audit_only', 'Solo auditoría'), ('archived', 'Archivado'), ('obsolete', 'Obsoleto'), ('shared', 'Legacy compartido'), ('private', 'Legacy privado')], default='shared', max_length=30),
        ),
        migrations.AlterField(
            model_name='supplierrfq',
            name='visibility',
            field=models.CharField(choices=[('public_shared', 'Compartido público controlado'), ('customer_shared', 'Compartido con cliente'), ('supplier_private', 'Privado Supplier'), ('supplier_confidential', 'Confidencial Supplier'), ('regulated_evidence', 'Evidencia regulada'), ('audit_only', 'Solo auditoría'), ('archived', 'Archivado'), ('obsolete', 'Obsoleto'), ('shared', 'Legacy compartido'), ('private', 'Legacy privado')], default='shared', max_length=30),
        ),
        migrations.AlterField(
            model_name='supplierscorecard',
            name='visibility',
            field=models.CharField(choices=[('public_shared', 'Compartido público controlado'), ('customer_shared', 'Compartido con cliente'), ('supplier_private', 'Privado Supplier'), ('supplier_confidential', 'Confidencial Supplier'), ('regulated_evidence', 'Evidencia regulada'), ('audit_only', 'Solo auditoría'), ('archived', 'Archivado'), ('obsolete', 'Obsoleto'), ('shared', 'Legacy compartido'), ('private', 'Legacy privado')], default='shared', max_length=30),
        ),
        migrations.AlterField(
            model_name='suppliershipment',
            name='visibility',
            field=models.CharField(choices=[('public_shared', 'Compartido público controlado'), ('customer_shared', 'Compartido con cliente'), ('supplier_private', 'Privado Supplier'), ('supplier_confidential', 'Confidencial Supplier'), ('regulated_evidence', 'Evidencia regulada'), ('audit_only', 'Solo auditoría'), ('archived', 'Archivado'), ('obsolete', 'Obsoleto'), ('shared', 'Legacy compartido'), ('private', 'Legacy privado')], default='shared', max_length=30),
        ),
        migrations.AddIndex(
            model_name='medsupplierauditevent',
            index=models.Index(fields=['organization', 'account', '-created_at'], name='medsupplier_organiz_488102_idx'),
        ),
        migrations.AddField(
            model_name='evidencepackage',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_packages', to='medsupplier.supplieraccount'),
        ),
        migrations.AddField(
            model_name='evidencepackage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencepackage',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_evidence_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencepackage',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization'),
        ),
        migrations.AddField(
            model_name='evidencepackage',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencepackageentry',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='medsupplier.evidencepackage'),
        ),
        migrations.AddField(
            model_name='medsupplieresignature',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esignatures', to='medsupplier.supplieraccount'),
        ),
        migrations.AddField(
            model_name='medsupplieresignature',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medsupplier_esignatures', to='core.organization'),
        ),
        migrations.AddField(
            model_name='medsupplieresignature',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medsupplier_esignatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medsupplieruserscope',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_scopes', to='medsupplier.supplieraccount'),
        ),
        migrations.AddField(
            model_name='medsupplieruserscope',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medsupplier_user_scopes', to='core.organization'),
        ),
        migrations.AddField(
            model_name='medsupplieruserscope',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medsupplier_scopes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierfmea',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fmeas', to='medsupplier.supplieraccount'),
        ),
        migrations.AddField(
            model_name='supplierfmea',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierfmea',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization'),
        ),
        migrations.AddField(
            model_name='supplierfmea',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierfmeaitem',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fmea_items', to='medsupplier.supplieraccount'),
        ),
        migrations.AddField(
            model_name='supplierfmeaitem',
            name='capa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fmea_items', to='medsupplier.suppliercapa'),
        ),
        migrations.AddField(
            model_name='supplierfmeaitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierfmeaitem',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fmea_items', to='medsupplier.supplierdocument'),
        ),
        migrations.AddField(
            model_name='supplierfmeaitem',
            name='fmea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medsupplier.supplierfmea'),
        ),
        migrations.AddField(
            model_name='supplierfmeaitem',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization'),
        ),
        migrations.AddField(
            model_name='supplierfmeaitem',
            name='quality_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fmea_items', to='medsupplier.supplierqualityevent'),
        ),
        migrations.AddField(
            model_name='supplierfmeaitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='medsupplier.supplieraccount'),
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization'),
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='medsupplier.supplierpurchaseorder'),
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierquoteline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_lines', to='medsupplier.supplieraccount'),
        ),
        migrations.AddField(
            model_name='supplierquoteline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierquoteline',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization'),
        ),
        migrations.AddField(
            model_name='supplierquoteline',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='medsupplier.supplierquote'),
        ),
        migrations.AddField(
            model_name='supplierquoteline',
            name='rfq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_lines', to='medsupplier.supplierrfq'),
        ),
        migrations.AddField(
            model_name='supplierquoteline',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='quote_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='medsupplier.supplierquoteline'),
        ),
        migrations.AddField(
            model_name='suppliershipmentmilestone',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_milestones', to='medsupplier.supplieraccount'),
        ),
        migrations.AddField(
            model_name='suppliershipmentmilestone',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suppliershipmentmilestone',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization'),
        ),
        migrations.AddField(
            model_name='suppliershipmentmilestone',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='medsupplier.suppliershipment'),
        ),
        migrations.AddField(
            model_name='suppliershipmentmilestone',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='evidencepackage',
            constraint=models.UniqueConstraint(fields=('organization', 'package_number'), name='uniq_medsupplier_evidence_package'),
        ),
        migrations.AddConstraint(
            model_name='evidencepackageentry',
            constraint=models.UniqueConstraint(fields=('package', 'object_type', 'object_id'), name='uniq_medsupplier_evidence_entry'),
        ),
        migrations.AddIndex(
            model_name='medsupplieresignature',
            index=models.Index(fields=['organization', 'object_type', 'object_id'], name='medsupplier_organiz_d57f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='medsupplieresignature',
            index=models.Index(fields=['user', '-signed_at'], name='medsupplier_user_id_9c1139_idx'),
        ),
        migrations.AddIndex(
            model_name='medsupplieruserscope',
            index=models.Index(fields=['organization', 'side', 'role'], name='medsupplier_organiz_e2822d_idx'),
        ),
        migrations.AddIndex(
            model_name='medsupplieruserscope',
            index=models.Index(fields=['user', 'organization', 'is_active'], name='medsupplier_user_id_fc2ddf_idx'),
        ),
        migrations.AddConstraint(
            model_name='medsupplieruserscope',
            constraint=models.UniqueConstraint(fields=('user', 'organization', 'account', 'role'), name='uniq_medsupplier_user_scope'),
        ),
        migrations.AddConstraint(
            model_name='supplierfmea',
            constraint=models.UniqueConstraint(fields=('organization', 'fmea_number'), name='uniq_medsupplier_fmea_number'),
        ),
        migrations.AddConstraint(
            model_name='supplierquoteline',
            constraint=models.UniqueConstraint(fields=('quote', 'line_number'), name='uniq_medsupplier_quote_line'),
        ),
        migrations.AddConstraint(
            model_name='supplierorderline',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'line_number'), name='uniq_medsupplier_order_line'),
        ),
    ]
