# Generated by Django 6.0.6 on 2026-06-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_featureflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
